field:
  corners: [[164, 442], [563, 438], [586, 22], [145, 23]] # точки карты
  width_m: 2.2         # ширина поля (м)
  height_m: 2.2        # высота поля (м)  
  origin: [164, 422]   # точка начала координат

robot:
  robot_id: "192.168.0.1"   # id для подключения робота
  robot_port: 80            # номер порта для подключения
  robot_diameter_m: 0.5     # диаметр робота (м)
  aruco_mount_angle_deg: 0  # угол поворота арукомаркера (градусы)

path_planner:
  # Выбор алгоритма: "astar", "bi_dijkstra", "greedy" или "apf"
  planner_type: "astar"
  dinamic_path: true           # Включает динамичсекое изменение пути 
  use_spline: true             # Включить сглаживание пути сплайном (true/false)
  spline_num_points: 150        # Количество точек в сглаженном пути (чем больше, тем плавнее)

  # Общие параметры (используются всеми алгоритмами)
  safety_margin: 0.13        # Безопасный отступ от препятствий и границ поля (м)
  obs_radius_m: 0.25        # Эффективный радиус препятствий для "раздувания" в сетке (м)
  waypoint_threshold: 0.075 # Допуск достижения точки пути (м)
  cell_size: 0.05           # Размер ячейки сетки (м)  

  # Параметры для A*
  astar:

  # Параметры для RRT* (Rapidly-exploring Random Tree Star)
  rrt_star:
    max_iterations: 2000     # Макс. число попыток построения дерева
    step_size: 0.05          # Макс. длина нового шага дерева (м)
    search_radius: 0.1       # Радиус поиска соседей для переподключения (rewiring) (м)

  # Параметры для APF (Artificial Potential Fields)
  apf:
    attractive_gain: 3.5     # Коэффициент притяжения к цели
    repulsive_gain: 2      # Коэффициент отталкивания от препятствий
    influence_radius: 0.1    # Дистанция, на которой начинает действовать отталкивание (м)
    step_size: 0.03           # Размер шага робота за одну итерацию (м)
    max_iterations: 600      # Макс. число шагов (защита от застревания в локальном минимуме)
    goal_threshold: 0.07     # Расстояние до цели, при котором движение считается завершённым (м)

navigation:
  speed_far_m_s: 0.5        # Скорость на дальнем участке (м/с)
  speed_near_m_s: 0.1      # Скорость вблизи цели (м/с)
  speed_threshold_m: 0.3    # Дистанция переключения скоростей (м)

recorded_path_test:
  enabled: true                  # false = обычный режим (клик мыши), true = режим авто-теста
  start_m: [0.43, 0.23]        # Будет перезаписано скриптом setup_recorded_path.py
  goal_m: [0.34, 1.86]         # Будет перезаписано скриптом setup_recorded_path.py

